development:
  adapter: postgresql
  encoding: unicode
  database: servicii_db
  pool: 5
  username: Axelut
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: servicii_db
  pool: 5
  username: Axelut
  password: